# Generated by Django 2.1.2 on 2018-10-30 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('search_token', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LectureData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('lecture_video_link', models.URLField(default='#', max_length=356)),
                ('previous_video_link', models.URLField(default='#', max_length=356)),
                ('next_video_link', models.URLField(default='#', max_length=356)),
                ('description', models.TextField()),
                ('enable_description', models.BooleanField(default=True)),
                ('search_token', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_data', to='school_app.CourseData')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='coursedata',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_data', to='school_app.SchoolData'),
        ),
    ]
