# Generated by Django 2.1.2 on 2018-10-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturedata',
            name='next_video_link',
            field=models.CharField(default='#', max_length=356),
        ),
        migrations.AlterField(
            model_name='lecturedata',
            name='previous_video_link',
            field=models.CharField(default='#', max_length=356),
        ),
    ]
