# Generated by Django 2.1.2 on 2018-10-31 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_auto_20181030_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturedata',
            name='next_video_link',
        ),
        migrations.RemoveField(
            model_name='lecturedata',
            name='previous_video_link',
        ),
    ]
