# Generated by Django 2.1.2 on 2018-11-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_auto_20181031_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldata',
            name='card_color',
            field=models.CharField(default='#ffff', max_length=256),
        ),
    ]
