# Generated by Django 2.1.2 on 2018-11-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_schooldata_card_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedata',
            name='model_name',
            field=models.CharField(default='CourseData', max_length=256),
        ),
        migrations.AddField(
            model_name='lecturedata',
            name='model_name',
            field=models.CharField(default='LectureData', max_length=256),
        ),
        migrations.AddField(
            model_name='schooldata',
            name='model_name',
            field=models.CharField(default='SchoolData', max_length=256),
        ),
    ]
